@isTest
public class testProjectsSummary {

    /*public testMethod static void testMethod1() {
    
        Vertiba_Project__c proj = new Vertiba_Project__c(Name='Lucian Test Project');
        insert proj;
    
        Vertiba_Project_Role__c pr1 = new Vertiba_Project_Role__c(Project__c = proj.Id);
        pr1.Hour_Budget__c = 100;
        insert pr1;
        
        Vertiba_Project_Role__c pr2 = new Vertiba_Project_Role__c(Project__c = proj.Id);
        pr2.Hour_Budget__c = 10;
        insert pr2;
                
        proj = [SELECT Hours_Budgeted__c FROM Vertiba_Project__c WHERE Id = :proj.Id];
        System.assertEquals(110, proj.Hours_Budgeted__c);
        
        pr2.Hour_Budget__c = 20;
        update pr2;
    
        proj = [SELECT Hours_Budgeted__c FROM Vertiba_Project__c WHERE Id = :proj.Id];
        System.assertEquals(120, proj.Hours_Budgeted__c);
        
        delete pr2;

        proj = [SELECT Hours_Budgeted__c FROM Vertiba_Project__c WHERE Id = :proj.Id];
        System.assertEquals(100, proj.Hours_Budgeted__c);
        
        delete pr1;

        proj = [SELECT Hours_Budgeted__c FROM Vertiba_Project__c WHERE Id = :proj.Id];
        System.assertEquals(0, proj.Hours_Budgeted__c);
        
    }*/

}